name: Release CI

on:
  push:
    tags: "v*" # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
      - name: Set env
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "RELEASE_NAME=${RELEASE_VERSION:1}" >> $GITHUB_ENV
      # 옵션: NPM에 추가한다면 이 부분 주석 제거 및 GitHub Secrets에 NPM_TOKEN 추가
      # - name: Publish to NPM
      #   run: |
      #     # Publish
      #     yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      #     yarn workspaces foreach run publish
      - name: Zip
        run: |
          cd packages

          # Remove Split Files
          find -wholename "**/webfonts/*/split*" -delete

          # Zip # 옵션: 다른 폰트 패키지를 추가한다면 아래 부분 복제 후 이름 바꾸기
          (cd template-font/fonts && zip -rv - .) > TemplateFont-${{ env.RELEASE_NAME }}.zip
      - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: # 옵션: 다른 폰트 패키지를 추가한다면 아래 zip 부분 복제 후 이름 바꾸기
          files: |
            packages/TemplateFont-${{ env.RELEASE_NAME }}.zip
